import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowTrendUp,
  faBriefcase,
  faBullseye,
  faCalendarDays,
  faChartArea,
  faChartLine,
  faCheck,
  faChevronDown,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClipboardList,
  faClock,
  faCodeCompare,
  faCoins,
  faCompass,
  faDice,
  faExclamation,
  faFlagCheckered,
  faGear,
  faHeartPulse,
  faHouse,
  faLandmark,
  faLightbulb,
  faMinus,
  faMoon,
  faPercent,
  faPiggyBank,
  faPlus,
  faReceipt,
  faScaleBalanced,
  faSliders,
  faSterlingSign,
  faSunBright,
  faTable,
  faTriangleExclamation,
  faUmbrellaBeach,
  faUser,
  faWallet,
} from "@fortawesome/pro-solid-svg-icons";

/**
 * Shared semantic icon registry.
 *
 * Existing top-level names remain available for backward compatibility, while
 * Project Polaris can use the grouped navigation, concepts and status names.
 */
export const AppIcons = {
  // Existing application icons
  home: faHouse,
  user: faUser,
  employment: faBriefcase,
  pension: faLandmark,
  retirement: faPiggyBank,
  goals: faBullseye,
  money: faSterlingSign,
  wallet: faWallet,
  coins: faCoins,
  chart: faChartArea,
  chartLine: faChartLine,
  growth: faArrowTrendUp,
  comparison: faScaleBalanced,
  fees: faPercent,
  health: faHeartPulse,
  recommendations: faLightbulb,
  milestones: faFlagCheckered,
  assumptions: faClipboardList,
  projection: faTable,
  check: faCheck,
  success: faCircleCheck,
  warning: faExclamation,
  minus: faMinus,
  plus: faPlus,
  chevronDown: faChevronDown,
  information: faCircleInfo,
  calendar: faCalendarDays,
  clock: faClock,
  sun: faSunBright,
  moon: faMoon,
  settings: faSliders,
  gear: faGear,

  // Project Polaris grouped icons
  navigation: {
    overview: faHouse,
    plan: faClipboardList,
    drawdown: faWallet,
    compare: faCodeCompare,
    explore: faCompass,
    guidance: faLightbulb,
  },
  concepts: {
    pension: faPiggyBank,
    income: faSterlingSign,
    projection: faChartLine,
    monteCarlo: faDice,
    tax: faReceipt,
    retirement: faUmbrellaBeach,
    settings: faSliders,
  },
  status: {
    success: faCircleCheck,
    warning: faCircleExclamation,
    danger: faTriangleExclamation,
    information: faCircleInfo,
  },
} as const;

export type AppIcon = IconDefinition;
